/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javafx_app.utilities;

import java.util.List;

public class StringUtils {
	public static String join(List<String> source) {
		return String.join(",", source);
	}
}
